package com.foxconn.cnsbg.escort.subsys.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CACHED_ALERT_MSG.
 */
public class CachedAlertMsg {

    private Long id;
    private String deviceID;
    private java.util.Date time;
    private String type;
    private String level;
    private String info;

    public CachedAlertMsg() {
    }

    public CachedAlertMsg(Long id) {
        this.id = id;
    }

    public CachedAlertMsg(Long id, String deviceID, java.util.Date time, String type, String level, String info) {
        this.id = id;
        this.deviceID = deviceID;
        this.time = time;
        this.type = type;
        this.level = level;
        this.info = info;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDeviceID() {
        return deviceID;
    }

    public void setDeviceID(String deviceID) {
        this.deviceID = deviceID;
    }

    public java.util.Date getTime() {
        return time;
    }

    public void setTime(java.util.Date time) {
        this.time = time;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getLevel() {
        return level;
    }

    public void setLevel(String level) {
        this.level = level;
    }

    public String getInfo() {
        return info;
    }

    public void setInfo(String info) {
        this.info = info;
    }

}
